name: FortressAssault
main: org.kokakiwi.ssell.fortressassault.FortressAssault
version: 1.2.0
commands:
    faStart:
        description: Starts the event.
        usage: /faStart
    faStop:
        description: Stops the event
        usage: /faStop
    faAdd:
        description: Adds player to team. RED or BLUE
        usage: /faAdd <Group> <Player>
    faRemove:
        description: Removes player from team.
        usage: /faRemove <Player>
    faTime:
        description: Sets time limit before the Assault.
        usage: /faTime <Time>
    faTeams:
        description: Get teams scores.
        usage: /faTeams
    faReturn:
        description: Leave the battle.
        usage: /faReturn